config/routes.rb
Rails.application.routes.draw do
  
  resources :baskets

  resources :users

  resources :products
  
  root 'static_pages#home'

  get 'home'        => 'static_pages#home'
  get 'novoproduto' => 'products#new'
  get 'produto'     => 'products#show'
  get 'basket'      => 'static_pages#basket'

end

app/models/basket.rb
class Basket < ActiveRecord::Base
	has_and_belongs_to_many :products
	belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_and_belongs_to_many :baskets
	has_many :users, through: :baskets 
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :products, through: :baskets
	has_one :basket
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_action :set_basket, only: [:show, :edit, :update, :destroy]

  # GET /baskets
  # GET /baskets.json
  def index
    @baskets = Basket.all
  end

  # GET /baskets/1
  # GET /baskets/1.json
  def show
  end

  # GET /baskets/new
  def new
    @basket = Basket.new
  end

  # GET /baskets/1/edit
  def edit
  end

  # POST /baskets
  # POST /baskets.json
  def create
    @basket = Basket.new(basket_params)

    respond_to do |format|
      if @basket.save
        format.html { redirect_to @basket, notice: 'Basket was successfully created.' }
        format.json { render :show, status: :created, location: @basket }
      else
        format.html { render :new }
        format.json { render json: @basket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /baskets/1
  # PATCH/PUT /baskets/1.json
  def update
    respond_to do |format|
      if @basket.update(basket_params)
        format.html { redirect_to @basket, notice: 'Basket was successfully updated.' }
        format.json { render :show, status: :ok, location: @basket }
      else
        format.html { render :edit }
        format.json { render json: @basket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /baskets/1
  # DELETE /baskets/1.json
  def destroy
    @basket.destroy
    respond_to do |format|
      format.html { redirect_to baskets_url, notice: 'Basket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_basket
      @basket = Basket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def basket_params
      params[:basket]
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new

    @product = Product.new

  end

  def create
    @product = Product.create(product_params) 
    @product = Product.new

    render :new
  end

  def index
    @products = Product.all

  end

  def show
    @product= Product.find(params[:id])
  end

  def update

    if @product = Product.update(params[:id],product_params) 
      redirect_to edit_product_path      
    end

  end

  def edit
    @product = Product.find(params[:id])
    
  end

  private
    def product_params
      params.require(:product).permit(:name,:preco,:image,:description)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@products = Product.all
  end

  def basket 
  	@product = Product.all
  end

  def product
  end

  def adicionar_produtos
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/baskets/_form.html.haml
<%= form_for(@basket) do |f| %>
  <% if @basket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@basket.errors.count, "error") %> prohibited this basket from being saved:</h2>

      <ul>
      <% @basket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/baskets/basket.html.haml
.row.box#basket
    .wrap
      .col-sm-5.col#product
        %h3 Produto
        .description
          .col-sm-4.col
            %img{:src=>"http://goo.gl/PQUZju",:class=>"img-responsive"}
          .col-sm-8.col
            %h4 Chapisco na Mantega
      .col-sm-2.col#price
        %h3 Preço
        %p.lead R$1000,00
      .col-sm-2.col#amount
        %h3 Quantidade 
        .counter
          .down.glyphicon.glyphicon-minus{'data-counter'=>'down'}
          %input{:type => "text", :class =>"amount", :value => 0} 
          .up.glyphicon.glyphicon-plus{'data-counter'=>'up'}
      .col-sm-2.col#total
        %h3 Total
        %p.lead R$ 3000,00

app/views/baskets/edit.html.haml
<h1>Editing basket</h1>

<%= render 'form' %>

<%= link_to 'Show', @basket %> |
<%= link_to 'Back', baskets_path %>

app/views/baskets/index.html.haml
.row.box#basket
  .wrap
    .col-sm-5.col#product
      %h3 Produto
      .description
        .col-sm-4.col
          %img{:src=>"http://goo.gl/PQUZju",:class=>"img-responsive"}
        .col-sm-8.col
          %h4 Chapisco na Mantega
    .col-sm-2.col#price
      %h3 Preço
      %p.lead R$1000,00
    .col-sm-2.col#amount
      %h3 Quantidade 
      .counter
        .down.glyphicon.glyphicon-minus{'data-counter'=>'down'}
        %input{:type => "text", :class =>"amount", :value => 0} 
        .up.glyphicon.glyphicon-plus{'data-counter'=>'up'}
    .col-sm-2.col#total
      %h3 Total
      %p.lead R$ 3000,00

app/views/baskets/new.html.haml
<h1>New basket</h1>

<%= render 'form' %>

<%= link_to 'Back', baskets_path %>

app/views/baskets/show.html.haml
.row.box#basket
    .wrap
      .col-sm-5.col#product
        %h3 Produto
        .description
          .col-sm-4.col
            %img{:src=>"http://goo.gl/PQUZju",:class=>"img-responsive"}
          .col-sm-8.col
            %h4 Chapisco na Mantega
      .col-sm-2.col#price
        %h3 Preço
        %p.lead R$1000,00
      .col-sm-2.col#amount
        %h3 Quantidade 
        .counter
          .down.glyphicon.glyphicon-minus{'data-counter'=>'down'}
          %input{:type => "text", :class =>"amount", :value => 0} 
          .up.glyphicon.glyphicon-plus{'data-counter'=>'up'}
      .col-sm-2.col#total
        %h3 Total
        %p.lead R$ 3000,00

app/views/layouts/application.html.haml
!!! 5
%html
	%head
		%title= yield(:title) 
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true 
		= csrf_meta_tags

	%body

		%header
			%nav.navbar.navbar-default.margin-zero
				.container-fluid
					.navbar-header
			.second-bar	
			.container
					
			
		%main
			.container
				= yield 

		%footer
			.container
				= image_tag "monukuruboo.svg", title:"monokorobo", alt:"monokorobo"
			.first-floor
			.second-floor

app/views/products/_counter.html.haml
.up-down
	.up.glyphicon.glyphicon-chevron-up{'data-counter'=>'up'}
	.down.glyphicon.glyphicon-chevron-down{'data-counter'=>'down'}
%input{:type => "text", :class =>"amount", :value => 0} 

app/views/products/create.html.haml
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/edit.html.haml
= provide(:title, 'Editar Produto')
.row
	.col-md-3
		%h1 Novo produto
		= form_for @product, :html =>{ class: "form-group" } do |f|
			
			.form-group
				= f.label :name, "Nome"
				= f.text_field :name, class: "form-control"

			.form-group
				= f.label :description, "Descrição"
				= f.text_area :description, class: "form-control"

			.form-group
				= f.label :image, "Localização da Imagem"
				= f.text_field :image, class: "form-control"

			.form-group
				= f.label :preco, "Preço"
				= f.text_field :preco, class: "form-control"

			=f.submit "Adicionar", class: "btn btn-success"

app/views/products/index.html.haml
- provide(:title,'Todos Produtos')

%h1 Todos os produtos
%ul.produtos
	- @products.each do |produto|
		%h3 Nome 
		%p= produto.name
		
		%h3 Preço
		%p R$= produto.preco

app/views/products/new.html.haml
= provide(:title, 'Novo Produto')
.row
	.col-md-3
		%h1 Novo produto
		= form_for @product, :html =>{ class: "form-group" } do |f|
			
			.form-group
				= f.label :name, "Nome"
				= f.text_field :name, class: "form-control"

			.form-group
				= f.label :description, "Descrição"
				= f.text_area :description, class: "form-control"

			.form-group
				= f.label :image, "Localização da Imagem"
				= f.text_field :image, class: "form-control"

			.form-group
				= f.label :preco, "Preço"
				= f.text_field :preco, class: "form-control"

			=f.submit "Adicionar", class: "btn btn-success"




app/views/products/show.html.haml
- provide :title, @product.name

.box.row
	.image.col-md-3.thumbnail
		= image_tag @product.image, class: "img-responsive" 
	.information.col-md-5
		%h2= @product.name
		%p=  @product.description
		.counter-button-preco
			%h3= "R$ #{@product.preco.to_s.gsub(/\./,',')}"
			.counter-button	
				.counter
					= render "counter"

				/ Button
				= link_to @product do
					%button{:class=> "btn btn-primary pull-right", :role => 'buttom'} Comprar
	%aside.additional-column.col-md-3
		
		

		
 

app/views/static_pages/basket.html.haml
.box#bastket
	.drop
		.glyphicon.glyphicon-minus
	.image
	.name
	.counter
		= render "products/counter"
	.preco
	.total

app/views/static_pages/home.html.haml
- provide(:title, "Início")


%ul.produtos.padding-zero
	- @products.in_groups_of(4) do |group|
		.row
			- group.each do |product|
				.col-sm-3
					.thumbnail
						= image_tag "#{product.image}"
						.caption
							%h3= product.name
							%p= "R$ #{product.preco}"
							%p.button
							= link_to product do
								%button{:class=> "btn btn-primary pull-right", :role => 'buttom'} Ver
									

app/views/static_pages/product.html.haml
%h1 ola

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>